spring:
  application:
    name: SpringBoot-AI-1
  ai:
    openai:
      api-key: ${GROQ_APIKEY}      
      base-url: https://api.groq.com/openai
      chat:
        options:
          model: llama3-70b-8192
